### ISSUE TITLE
Could not instantiate mail function

### ISSUE THREAD

**Issue by Saboteur777** [angusfretwell/craftsman#50]
I got the following error:

Craft\Exception
E-mail error: Could not instantiate mail function

**/var/www/craft/app/services/EmailService.php(475)**
```
if ($errorMessage)
466             {
467                 // Fire an 'onSendEmailError' event
468                 $this->onSendEmailError(new Event($this, array(
469                     'user' => $user,
470                     'emailModel' => $emailModel,
471                     'variables' => $variables,
472                     'error' => $errorMessage,
473                 )));
474 
475                 throw new Exception(Craft::t('Email error: {error}', array('error' => $errorMessage)));
476             }
477 
```

[Craft_Exception.pdf](https://github.com/angusfretwell/craftsman/files/771291/Craft_Exception.pdf)

**Comment by angusfretwell** [comment]
Hey @Saboteur777, did you mean to make the issue here, or on gabrielmoreira/craftman?

Craftsman (this repo) doesn't support the built in `mail` function, since it provides no mail server. I suspect gabrielmoreira/craftman may have the same issue. I would suggest using something like Mailgun. In your development environment, you could use Gmail or Mailcatcher. You could add Mailcatcher to docker-compose using this image: https://hub.docker.com/r/schickling/mailcatcher/

**Comment by Saboteur777** [comment]
Jesus, I am noob... 😁 Yeah, I meant to make this issue on gabrielmoreira/craftman. 

I will look into this Mailcatcher thing, thank you!
